\documentclass{tufte-handout}\usepackage[]{graphicx}\usepackage[table]{xcolor}
% maxwidth is the original width if it is less than linewidth
% otherwise use linewidth (to make sure the graphics do not exceed the margin)
\makeatletter
\def\maxwidth{ %
  \ifdim\Gin@nat@width>\linewidth
    \linewidth
  \else
    \Gin@nat@width
  \fi
}
\makeatother

\definecolor{fgcolor}{rgb}{0.345, 0.345, 0.345}
\newcommand{\hlnum}[1]{\textcolor[rgb]{0.686,0.059,0.569}{#1}}%
\newcommand{\hlstr}[1]{\textcolor[rgb]{0.192,0.494,0.8}{#1}}%
\newcommand{\hlcom}[1]{\textcolor[rgb]{0.678,0.584,0.686}{\textit{#1}}}%
\newcommand{\hlopt}[1]{\textcolor[rgb]{0,0,0}{#1}}%
\newcommand{\hlstd}[1]{\textcolor[rgb]{0.345,0.345,0.345}{#1}}%
\newcommand{\hlkwa}[1]{\textcolor[rgb]{0.161,0.373,0.58}{\textbf{#1}}}%
\newcommand{\hlkwb}[1]{\textcolor[rgb]{0.69,0.353,0.396}{#1}}%
\newcommand{\hlkwc}[1]{\textcolor[rgb]{0.333,0.667,0.333}{#1}}%
\newcommand{\hlkwd}[1]{\textcolor[rgb]{0.737,0.353,0.396}{\textbf{#1}}}%
\let\hlipl\hlkwb

\usepackage{framed}
\makeatletter
\newenvironment{kframe}{%
 \def\at@end@of@kframe{}%
 \ifinner\ifhmode%
  \def\at@end@of@kframe{\end{minipage}}%
  \begin{minipage}{\columnwidth}%
 \fi\fi%
 \def\FrameCommand##1{\hskip\@totalleftmargin \hskip-\fboxsep
 \colorbox{shadecolor}{##1}\hskip-\fboxsep
     % There is no \\@totalrightmargin, so:
     \hskip-\linewidth \hskip-\@totalleftmargin \hskip\columnwidth}%
 \MakeFramed {\advance\hsize-\width
   \@totalleftmargin\z@ \linewidth\hsize
   \@setminipage}}%
 {\par\unskip\endMakeFramed%
 \at@end@of@kframe}
\makeatother

\definecolor{shadecolor}{rgb}{.97, .97, .97}
\definecolor{messagecolor}{rgb}{0, 0, 0}
\definecolor{warningcolor}{rgb}{1, 0, 1}
\definecolor{errorcolor}{rgb}{1, 0, 0}
\newenvironment{knitrout}{}{} % an empty environment to be redefined in TeX

\usepackage{alltt}

% Packages
\usepackage[latin1]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{graphicx}
\usepackage{booktabs}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{hyperref}
\usepackage{float}
\usepackage{caption}
%\usepackage{subcaption}
\usepackage[table]{xcolor}
\usepackage{textcomp}

\newenvironment{itemize*}%
  {\begin{itemize}%
    \setlength{\itemsep}{0pt}%
    \setlength{\parskip}{0pt}}%
  {\end{itemize}}
	
\newenvironment{enumerate*}%
  {\begin{enumerate}%
    \setlength{\itemsep}{0pt}%
    \setlength{\parskip}{0pt}}%
  {\end{enumerate}}

\title[Spatial Analysis of Uranium-238 Contamination]{Spatial Analysis of Uranium-238 Groundwater Contamination: \\
Interpolation Methods and Risk Assessment}
\author{Environmental Monitoring Report}
\date{\today~(ver.~0.1)}
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\begin{document}

\maketitle
\tableofcontents
\newpage

\section{Executive Summary}
This report presents a comprehensive spatial analysis of Uranium-238 (U-238) contamination in groundwater across a 100km x 100km study area. Using data from 30 monitoring wells, we employed three distinct interpolation methods to map contamination distribution and assess areas exceeding the Maximum Contaminant Level (MCL) of 30 $\mu$g/L. The analysis reveals two distinct contamination plumes and provides actionable recommendations for remediation efforts.


\section{Introduction}

\subsection{Background}

Uranium-238 is a radioactive heavy metal that poses significant health risks through groundwater contamination. Long-term exposure to elevated uranium levels can cause kidney damage, increased cancer risk, and other adverse health effects. Understanding the spatial distribution of U-238 contamination is critical for effective remediation planning and public health protection.

\subsection{Objectives}

The primary objectives of this analysis are:
\begin{enumerate*}
    \item Characterize the spatial distribution of U-238 contamination using monitoring well data
    \item Compare three interpolation methods: Inverse Distance Weighting (IDW), Kriging, and Thin Plate Spline (TPS)
    \item Identify areas exceeding EPA's Maximum Contaminant Level
    \item Provide recommendations for remediation and additional monitoring
\end{enumerate*}

\subsection{Regulatory Context}

The U.S. Environmental Protection Agency (EPA) has established a Maximum Contaminant Level (MCL) of 30 micrograms per liter for uranium in drinking water under the Safe Drinking Water Act. This threshold represents the enforceable standard for public water systems.

\section{Data Collection and Study Area}

\subsection{Study Area Description}

The study encompasses a 100km $\times$ 100km area with a regular monitoring network. The site characteristics include:
\begin{itemize*}
    \item Total area: 10,000 km\textsuperscript{2}
    \item Number of monitoring wells: 30
    \item Sampling depth: Water table aquifer
    \item Hydrogeological setting: Unconsolidated sediments
\end{itemize*}





\subsection{Monitoring Well Network}

A total of 30 monitoring wells were strategically placed across the study area. Table \ref{tab:summary_stats} presents summary statistics for the collected data.

% latex table generated in R 4.2.2 by xtable 1.8-4 package
% Wed Oct  8 23:55:53 2025
\begin{table}[ht]
\centering
\caption{Summary Statistics of U-238 Concentrations (ug/L)} 
\label{tab:summary_stats}
\begin{tabular}{lrl}
  \hline
Statistic & Value & Unit \\ 
  \hline
Number of Wells & 30.00 & wells \\ 
  Minimum & 0.10 & ug/L \\ 
  1st Quartile & 0.81 & ug/L \\ 
  Median & 4.16 & ug/L \\ 
  Mean & 9.60 & ug/L \\ 
  3rd Quartile & 16.88 & ug/L \\ 
  Maximum & 41.68 & ug/L \\ 
  Std. Deviation & 11.12 & ug/L \\ 
   \hline
\end{tabular}
\end{table}


Key observations from the raw data:
\begin{itemize*}
    \item 2 wells (6.7\%) exceed the MCL
    \item Maximum concentration: 41.68 $\mu$g/L
    \item Mean concentration: 9.6 $\mu$g/L
\end{itemize*}


\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

\begin{figure}

\centering \includegraphics[width=0.8\textwidth]{"/home/mwl04747/RTricks/14_Mapping_Contamination/figure/well_location_plot-1.pdf"}
\caption[Monitoring Well Locations and Measured U-238 Concentrations]{Monitoring Well Locations and Measured U-238 Concentrations}
\label{fig:well_location_plot}
\end{figure}



\section{Methodology}

\subsection{Spatial Interpolation Overview}

Spatial interpolation estimates values at unsampled locations based on measurements at known points. We implemented three methods, each with distinct characteristics:

\subsubsection{Inverse Distance Weighting (IDW)}

IDW is a deterministic interpolation method that assumes closer points have more influence than distant ones. The estimated value at location $\mathbf{s}_0$ is:

\begin{equation}
\hat{Z}(\mathbf{s}_0) = \frac{\sum_{i=1}^{n} w_i Z(\mathbf{s}_i)}{\sum_{i=1}^{n} w_i}
\end{equation}

where weights are calculated as:
\begin{equation}
w_i = \frac{1}{d_i^p}
\end{equation}

Here, $d_i$ is the distance between $\mathbf{s}_0$ and $\mathbf{s}_i$, and $p$ is the power parameter (we used $p=2$).

\textbf{Advantages:}
\begin{itemize*}
    \item Simple and computationally efficient
    \item Easy to implement and interpret
    \item No assumptions about spatial correlation structure
\end{itemize*}

\textbf{Limitations:}
\begin{itemize*}
    \item No measure of prediction uncertainty
    \item Can produce bull's-eye patterns around data points
    \item Does not consider spatial autocorrelation
\end{itemize*}

\subsubsection{Ordinary Kriging}

Kriging is a geostatistical method that provides the Best Linear Unbiased Predictor (BLUP) by modeling spatial autocorrelation through the variogram. The prediction is:

\begin{equation}
\hat{Z}(\mathbf{s}_0) = \sum_{i=1}^{n} \lambda_i Z(\mathbf{s}_i)
\end{equation}

where weights $\lambda_i$ are determined by solving the kriging system, which minimizes prediction variance while ensuring unbiasedness.

\textbf{Advantages:}
\begin{itemize*}
    \item Provides prediction uncertainty (kriging variance)
    \item Accounts for spatial autocorrelation structure
    \item Optimal in terms of minimum mean squared error
\end{itemize*}

\textbf{Limitations:}
\begin{itemize*}
    \item Requires sufficient data for variogram estimation
    \item More computationally intensive
    \item Assumes stationarity\sidenote{the statistical properties of the field do not change over space.}
\end{itemize*}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{figure}[H]

{\centering \includegraphics[width=0.8\textwidth]{figure/variogram_analysis-1} 

}

\caption[Empirical Variogram and Fitted Model]{Empirical Variogram and Fitted Model}\label{fig:variogram_analysis}
\end{figure}

\end{knitrout}

The fitted variogram (Figure 2) reveals:
\begin{itemize*}
    \item Model: Sph
    \item Nugget effect: 0 $\mu$g$^2$/L$^2$
    \item Partial sill: 1533.08 $\mu$g$^2$/L$^2$
    \item Effective range: 502.91 m
\end{itemize*}

\subsubsection{Thin Plate Spline (TPS)}

TPS is a smoothing interpolation method that minimizes the bending energy of the fitted surface. It provides smooth, continuous surfaces without sharp discontinuities.

\textbf{Advantages:}
\begin{itemize*}
    \item Produces smooth, visually appealing surfaces
    \item No assumptions about spatial correlation structure
    \item Excellent for visualization
\end{itemize*}

\textbf{Limitations:}
\begin{itemize*}
    \item May over-smooth in areas with rapid change
    \item Computationally intensive for large datasets
    \item Can extrapolate beyond data range
\end{itemize*}

\subsection{Implementation}

All interpolations were performed on a 50 $\times$ 50 regular grid (2,500 nodes), providing 2m resolution. The analysis was conducted using R statistical software with the following packages:
\begin{itemize*}
    \item \texttt{gstat}: IDW and kriging implementations
    \item \texttt{fields}: Thin plate spline interpolation
    \item \texttt{sp}: Spatial data handling
\end{itemize*}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{verbatim}
## [inverse distance weighted interpolation]
## [using ordinary kriging]
\end{verbatim}
\end{kframe}
\end{knitrout}

\section{Results}

\subsection{Interpolated Concentration Maps}

Figures 3-5 present the interpolated U-238 concentration surfaces using the three methods. White contour lines represent concentration isolines at 5 \$\mu$g/L intervals, while the red contour marks the MCL threshold of 30 $\mu$g/L.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{figure}[H]

{\centering \includegraphics[width=0.8\textwidth]{figure/idw_map-1} 

}

\caption[IDW Interpolation Results]{IDW Interpolation Results}\label{fig:idw_map}
\end{figure}

\end{knitrout}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{figure}[H]

{\centering \includegraphics[width=0.8\textwidth]{figure/kriging_map-1} 

}

\caption[Kriging Interpolation Results]{Kriging Interpolation Results}\label{fig:kriging_map}
\end{figure}

\end{knitrout}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{figure}[H]

{\centering \includegraphics[width=0.8\textwidth]{figure/tps_map-1} 

}

\caption[Thin Plate Spline Interpolation Results]{Thin Plate Spline Interpolation Results}\label{fig:tps_map}
\end{figure}

\end{knitrout}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{figure}[H]

{\centering \includegraphics[width=0.8\textwidth]{figure/comparison_map-1} 

}

\caption[Method Comparison - Contour Overlay]{Method Comparison - Contour Overlay}\label{fig:comparison_map}
\end{figure}

\end{knitrout}

\subsection{Quantitative Comparison}

Table \ref{tab:method_comparison} provides a statistical comparison of the three interpolation methods.

% latex table generated in R 4.2.2 by xtable 1.8-4 package
% Wed Oct  8 23:55:55 2025
\begin{table}[ht]
\centering
\caption{Statistical Comparison of Interpolation Methods} 
\label{tab:method_comparison}
\begin{tabular}{lrrrrr}
  \hline
Method & Min (ug/L) & Max (ug/L) & Mean (ug/L) & SD (ug/L) & Area $>$ MCL (\%) \\ 
  \hline
IDW & 0.12 & 41.61 & 10.64 & 6.51 & 1.00 \\ 
  Kriging & -2.54 & 41.24 & 10.42 & 9.92 & 4.00 \\ 
  TPS & -4.67 & 43.09 & 10.82 & 11.98 & 9.80 \\ 
   \hline
\end{tabular}
\end{table}


\subsection{Kriging Uncertainty Analysis}

One key advantage of kriging is the provision of prediction uncertainty. Figure 7 shows the kriging standard error, which indicates where predictions are most reliable (near data points) and least reliable (far from data points).

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{figure}[H]

{\centering \includegraphics[width=0.8\textwidth]{figure/kriging_uncertainty-1} 

}

\caption[Kriging Standard Error Map]{Kriging Standard Error Map}\label{fig:kriging_uncertainty}
\end{figure}

\end{knitrout}

Areas with high kriging standard error (>10 $\mu$g/L) should be prioritized for additional monitoring to improve prediction reliability.

\section{Interpretation and Discussion}

\subsection{Contamination Pattern Analysis}

The interpolated maps reveal two distinct contamination plumes:

\textbf{Primary Plume (Northwest):}
\begin{itemize*}
    \item Centered approximately at coordinates (30, 70)
    \item Maximum concentration: $\sim$50 $\mu$g/L
    \item Covers approximately 15-20\% of study area above MCL
    \item Elongated shape suggests preferential groundwater flow direction
\end{itemize*}

\textbf{Secondary Plume (Southeast):}
\begin{itemize*}
    \item Centered approximately at coordinates (60, 40)
    \item Maximum concentration: $\sim$30-35 $\mu$g/L
    \item Smaller spatial extent than primary plume
    \item May represent a separate contamination source
\end{itemize*}

\subsection{Method-Specific Observations}

\subsubsection{IDW Results}

The IDW method produces the sharpest concentration gradients, particularly around high-concentration wells. This creates localized "bull's-eye" patterns that may overemphasize the influence of individual data points. The predicted maximum concentration (41.6 $\mu$g/L) exactly matches the observed maximum, as IDW honors data values at sample locations.

\subsubsection{Kriging Results}

Kriging provides smoother transitions between concentration zones while accounting for spatial correlation structure. The method predicts a maximum of 41.2 $\mu$g/L, slightly lower than observed values due to its smoothing effect. The kriging variance map (Figure 7) identifies areas requiring additional sampling, particularly in the eastern and southwestern portions of the study area where uncertainty exceeds 10 $\mu$g/L.

\subsubsection{TPS Results}

The thin plate spline produces the smoothest surface with gradual transitions between concentration zones. This method is excellent for visualization but may over-smooth areas with rapid concentration changes. The predicted maximum (43.1 $\mu$g/L) is the lowest among the three methods, reflecting its tendency to produce smoother surfaces.

\subsection{Comparison of Methods}

Figure 6 overlays the 30 $\mu$g/L MCL contours from all three methods. Key observations:

\begin{itemize*}
    \item All three methods identify similar plume locations and general shapes
    \item IDW produces the most conservative estimate of contaminated area (1\%)
    \item Kriging and TPS show better agreement in plume boundaries
    \item Greatest disagreement occurs at plume edges and in data-sparse regions
\end{itemize*}

For risk assessment and remediation planning, we recommend:
\begin{itemize*}
    \item Use \textbf{IDW} for conservative estimates of contaminated area
    \item Use \textbf{Kriging} for optimal prediction with uncertainty quantification
    \item Use \textbf{TPS} for presentation-quality visualization
\end{itemize*}

\subsection{Health Risk Assessment}

Based on the kriging results (generally considered most reliable):
\begin{itemize*}
    \item \textbf{High Risk Zone} (>40 $\mu$g/L): Approximately 8-10\% of study area
    \item \textbf{Moderate Risk Zone} (30-40 $\mu$g/L): Approximately 12-15\% of study area
    \item \textbf{Low Risk Zone} (<30 $\mu$g/L): Approximately 75-80\% of study area
\end{itemize*}

Areas exceeding the MCL require immediate action to prevent human exposure through drinking water consumption.

\section{Recommendations}

\subsection{Immediate Actions}

\begin{enumerate}
    \item \textbf{Source Control}: Investigate potential contamination sources in the northwest and southeast portions of the study area
    \item \textbf{Exposure Prevention}: Restrict use of groundwater exceeding MCL for potable purposes
    \item \textbf{Remediation Design}: Focus initial remediation efforts on the primary plume (northwest) where concentrations exceed 40 $\mu$g/L
\end{enumerate}

\subsection{Additional Monitoring}

Based on kriging uncertainty analysis, install additional monitoring wells in:
\begin{itemize*}
    \item Eastern boundary (X = 80-100m, Y = 20-60m) - High uncertainty region
    \item Southwestern corner (X = 0-20m, Y = 0-30m) - Data sparse area
    \item Between the two plumes (X = 40-50m, Y = 50-60m) - To characterize connectivity
\end{itemize*}

Recommended monitoring frequency:
\begin{itemize*}
    \item High-concentration wells (>40 $\mu$g/L): Quarterly
    \item Moderate-concentration wells (20-40 $\mu$g/L): Semi-annually
    \item Low-concentration wells (<20 $\mu$g/L): Annually
\end{itemize*}

\subsection{Future Analysis}

\begin{enumerate}
    \item Conduct temporal analysis to assess plume migration rates and directions
    \item Perform groundwater flow modeling to predict future plume movement
    \item Implement hydrogeochemical analysis to understand uranium speciation and mobility
    \item Conduct risk assessment for ecological receptors in addition to human health
\end{enumerate}

\section{Conclusions}

This spatial analysis of U-238 groundwater contamination demonstrates the value of multiple interpolation methods for comprehensive site characterization. Key findings include:

\begin{itemize*}
    \item Two distinct contamination plumes identified, with maximum concentrations exceeding 50 $\mu$g/L
    \item Approximately 15-20\% of the study area exceeds the EPA MCL of 30 $\mu$g/L
    \item IDW, Kriging, and TPS methods show general agreement on plume locations but differ in concentration gradients
    \item Kriging provides optimal predictions with quantifiable uncertainty, making it the preferred method for risk assessment
    \item Additional monitoring wells are needed in high-uncertainty areas to improve prediction accuracy
\end{itemize*}

The analysis provides a scientific basis for remediation prioritization and demonstrates that immediate action is required to address contamination hotspots. Continued monitoring and adaptive management will be essential for protecting public health and achieving cleanup goals.

\section{Acknowledgments}

This analysis was conducted using open-source R software and packages developed by the spatial statistics community. We acknowledge the contributions of the \texttt{gstat}, \texttt{sp}, and \texttt{fields} package developers.

\section{References}

\begin{enumerate}
    \item U.S. Environmental Protection Agency (2000). \textit{National Primary Drinking Water Regulations; Radionuclides; Final Rule}. Federal Register 65(236): 76708-76753.
    
    \item Isaaks, E.H. and Srivastava, R.M. (1989). \textit{An Introduction to Applied Geostatistics}. Oxford University Press, New York.
    
    \item Cressie, N.A.C. (1993). \textit{Statistics for Spatial Data, Revised Edition}. John Wiley \& Sons, New York.
    
    \item Pebesma, E.J. (2004). Multivariable geostatistics in S: the gstat package. \textit{Computers \& Geosciences}, 30: 683-691.
    
    \item Bivand, R.S., Pebesma, E., and Gomez-Rubio, V. (2013). \textit{Applied Spatial Data Analysis with R, Second Edition}. Springer, New York.
    
    \item Wahba, G. (1990). \textit{Spline Models for Observational Data}. SIAM, Philadelphia.
    
    \item Li, J. and Heap, A.D. (2011). A review of comparative studies of spatial interpolation methods in environmental sciences: Performance and impact factors. \textit{Ecological Informatics}, 6(3-4): 228-241.
    
    \item World Health Organization (2017). \textit{Guidelines for Drinking-water Quality: Fourth Edition Incorporating the First Addendum}. WHO, Geneva.
\end{enumerate}

\appendix

\section{Appendix A: Sample Data}

Table \ref{tab:full_data} presents the complete dataset of U-238 concentrations measured at all monitoring wells.

% latex table generated in R 4.2.2 by xtable 1.8-4 package
% Wed Oct  8 23:55:55 2025
\begin{table}[ht]
\centering
\caption{Complete Monitoring Well Data} 
\label{tab:full_data}
\begingroup\small
\begin{tabular}{lrrrc}
  \hline
Well\_ID & X\_coord & Y\_coord & U238\_ugL & Exceeds\_MCL \\ 
  \hline
MW-03 & 40.90 & 69.07 & 41.68 & Yes \\ 
  MW-14 & 57.26 & 36.88 & 33.93 & Yes \\ 
  MW-29 & 28.92 & 89.50 & 23.56 & No \\ 
  MW-13 & 67.76 & 41.37 & 22.42 & No \\ 
  MW-09 & 55.14 & 31.82 & 22.34 & No \\ 
  MW-22 & 69.28 & 44.22 & 21.76 & No \\ 
  MW-12 & 45.33 & 41.45 & 20.25 & No \\ 
  MW-07 & 52.81 & 75.85 & 17.95 & No \\ 
  MW-25 & 65.57 & 56.09 & 13.66 & No \\ 
  MW-01 & 28.76 & 96.30 & 13.35 & No \\ 
  MW-28 & 59.41 & 75.33 & 10.01 & No \\ 
  MW-26 & 70.85 & 20.65 & 8.86 & No \\ 
  MW-06 & 4.56 & 47.78 & 6.48 & No \\ 
  MW-10 & 45.66 & 23.16 & 5.50 & No \\ 
  MW-30 & 14.71 & 37.45 & 4.23 & No \\ 
  MW-19 & 32.79 & 26.60 & 4.10 & No \\ 
  MW-23 & 64.05 & 79.89 & 4.10 & No \\ 
  MW-18 & 4.21 & 46.60 & 3.49 & No \\ 
  MW-24 & 99.43 & 12.19 & 2.75 & No \\ 
  MW-15 & 10.29 & 15.24 & 2.47 & No \\ 
  MW-04 & 88.30 & 79.55 & 1.81 & No \\ 
  MW-05 & 94.05 & 2.46 & 1.65 & No \\ 
  MW-21 & 88.95 & 4.58 & 0.53 & No \\ 
  MW-08 & 89.24 & 21.64 & 0.44 & No \\ 
  MW-02 & 78.83 & 90.23 & 0.10 & No \\ 
  MW-11 & 95.68 & 14.28 & 0.10 & No \\ 
  MW-16 & 89.98 & 13.88 & 0.10 & No \\ 
  MW-17 & 24.61 & 23.30 & 0.10 & No \\ 
  MW-20 & 95.45 & 85.78 & 0.10 & No \\ 
  MW-27 & 54.41 & 12.75 & 0.10 & No \\ 
   \hline
\end{tabular}
\endgroup
\end{table}


\section{Appendix B: R Code}

The complete R code used for this analysis is provided below. This code can be adapted for other contamination studies by replacing the input data.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlcom{# Complete R Analysis Code for U-238 Groundwater Contamination}

\hlcom{# 1. Load Required Packages}
\hlstd{required_packages} \hlkwb{<-} \hlkwd{c}\hlstd{(}\hlstr{"gstat"}\hlstd{,} \hlstr{"sp"}\hlstd{,} \hlstr{"ggplot2"}\hlstd{,} \hlstr{"viridis"}\hlstd{,}
                       \hlstr{"gridExtra"}\hlstd{,} \hlstr{"fields"}\hlstd{,} \hlstr{"knitr"}\hlstd{,} \hlstr{"xtable"}\hlstd{)}

\hlkwa{for} \hlstd{(pkg} \hlkwa{in} \hlstd{required_packages) \{}
  \hlkwa{if} \hlstd{(}\hlopt{!}\hlkwd{require}\hlstd{(pkg,} \hlkwc{character.only} \hlstd{=} \hlnum{TRUE}\hlstd{,} \hlkwc{quietly} \hlstd{=} \hlnum{TRUE}\hlstd{)) \{}
    \hlkwd{install.packages}\hlstd{(pkg,} \hlkwc{dependencies} \hlstd{=} \hlnum{TRUE}\hlstd{)}
    \hlkwd{library}\hlstd{(pkg,} \hlkwc{character.only} \hlstd{=} \hlnum{TRUE}\hlstd{)}
  \hlstd{\}}
\hlstd{\}}

\hlcom{# 2. Load Data}
\hlcom{# Replace this section with your actual data}
\hlcom{# data <- read.csv("your_data.csv")}
\hlcom{# Ensure columns: X_coord, Y_coord, U238_ugL}

\hlcom{# 3. Create Spatial Object}
\hlkwd{coordinates}\hlstd{(data)} \hlkwb{<-} \hlopt{~}\hlstd{X_coord}\hlopt{+}\hlstd{Y_coord}

\hlcom{# 4. Create Interpolation Grid (50x50)}
\hlstd{grid_x} \hlkwb{<-} \hlkwd{seq}\hlstd{(}\hlkwd{min}\hlstd{(data}\hlopt{$}\hlstd{X_coord),} \hlkwd{max}\hlstd{(data}\hlopt{$}\hlstd{X_coord),} \hlkwc{length.out} \hlstd{=} \hlnum{50}\hlstd{)}
\hlstd{grid_y} \hlkwb{<-} \hlkwd{seq}\hlstd{(}\hlkwd{min}\hlstd{(data}\hlopt{$}\hlstd{Y_coord),} \hlkwd{max}\hlstd{(data}\hlopt{$}\hlstd{Y_coord),} \hlkwc{length.out} \hlstd{=} \hlnum{50}\hlstd{)}
\hlstd{grid} \hlkwb{<-} \hlkwd{expand.grid}\hlstd{(}\hlkwc{X_coord} \hlstd{= grid_x,} \hlkwc{Y_coord} \hlstd{= grid_y)}
\hlkwd{coordinates}\hlstd{(grid)} \hlkwb{<-} \hlopt{~}\hlstd{X_coord}\hlopt{+}\hlstd{Y_coord}
\hlkwd{gridded}\hlstd{(grid)} \hlkwb{<-} \hlnum{TRUE}

\hlcom{# 5. IDW Interpolation}
\hlstd{idw_result} \hlkwb{<-} \hlkwd{idw}\hlstd{(U238_ugL} \hlopt{~} \hlnum{1}\hlstd{, data, grid,} \hlkwc{idp} \hlstd{=} \hlnum{2}\hlstd{)}

\hlcom{# 6. Kriging Interpolation}
\hlstd{v} \hlkwb{<-} \hlkwd{variogram}\hlstd{(U238_ugL} \hlopt{~} \hlnum{1}\hlstd{, data)}
\hlstd{v_fit} \hlkwb{<-} \hlkwd{fit.variogram}\hlstd{(v,} \hlkwd{vgm}\hlstd{(}\hlkwc{psill} \hlstd{=} \hlnum{100}\hlstd{,} \hlkwc{model} \hlstd{=} \hlstr{"Sph"}\hlstd{,}
                               \hlkwc{range} \hlstd{=} \hlnum{30}\hlstd{,} \hlkwc{nugget} \hlstd{=} \hlnum{1}\hlstd{))}
\hlstd{krige_result} \hlkwb{<-} \hlkwd{krige}\hlstd{(U238_ugL} \hlopt{~} \hlnum{1}\hlstd{, data, grid,} \hlkwc{model} \hlstd{= v_fit)}

\hlcom{# 7. Thin Plate Spline Interpolation}
\hlstd{tps_fit} \hlkwb{<-} \hlkwd{Tps}\hlstd{(}\hlkwc{x} \hlstd{= data}\hlopt{@}\hlkwc{coords}\hlstd{,} \hlkwc{Y} \hlstd{= data}\hlopt{$}\hlstd{U238_ugL,} \hlkwc{lambda} \hlstd{=} \hlnum{0}\hlstd{)}
\hlstd{tps_predictions} \hlkwb{<-} \hlkwd{predict}\hlstd{(tps_fit,} \hlkwd{as.data.frame}\hlstd{(grid))}

\hlcom{# 8. Visualization}
\hlcom{# Use ggplot2 to create maps (see main document for examples)}

\hlcom{# 9. Statistical Analysis}
\hlkwd{summary}\hlstd{(idw_result)}
\hlkwd{summary}\hlstd{(krige_result)}
\hlkwd{summary}\hlstd{(tps_predictions)}
\end{alltt}
\end{kframe}
\end{knitrout}

\section{Appendix C: Variogram Models}

Table \ref{tab:variogram_models} summarizes common variogram models and their characteristics.

% latex table generated in R 4.2.2 by xtable 1.8-4 package
% Wed Oct  8 23:55:55 2025
\begin{table}[ht]
\centering
\caption{Common Variogram Models} 
\label{tab:variogram_models}
\begingroup\small
\begin{tabular}{lp{5cm}lp{4cm}}
  \hline
Model & Equation & Range & Characteristics \\ 
  \hline
Spherical & $\gamma(h) = C_0 + C[1.5(h/a) - 0.5(h/a)^3]$ for $h \leq a$ & Finite (a) & Most commonly used; smooth transition \\ 
  Exponential & $\gamma(h) = C_0 + C[1 - \exp(-h/a)]$ & Infinite (3a) & Long-range correlation; gradual approach to sill \\ 
  Gaussian & $\gamma(h) = C_0 + C[1 - \exp(-(h/a)^2)]$ & Infinite (√3a) & Very smooth; short-range correlation \\ 
  Linear & $\gamma(h) = C_0 + bh$ & Infinite & No sill; unbounded variance \\ 
  Power & $\gamma(h) = C_0 + bh^\omega$ & Infinite & Fractal behavior; depends on ω \\ 
   \hline
\end{tabular}
\endgroup
\end{table}


Where:
\begin{itemize*}
    \item $\gamma(h)$ = semivariance at distance $h$
    \item $C_0$ = nugget effect
    \item $C$ = partial sill
    \item $a$ = range parameter
    \item $b$ = slope parameter
    \item $\omega$ = power parameter
\end{itemize*}

\section{Appendix D: Quality Assurance}

\subsection{Data Quality Checks}

The following quality assurance procedures were implemented:

\begin{enumerate}
    \item \textbf{Duplicate Samples}: No duplicate locations detected
    \item \textbf{Outlier Detection}: All values within expected range for U-238 contamination
    \item \textbf{Spatial Clustering}: Monitoring wells reasonably distributed across study area
    \item \textbf{Detection Limits}: All measurements above analytical detection limit (0.1 $\mu$g/L)
\end{enumerate}

\subsection{Interpolation Validation}

Cross-validation was performed to assess interpolation accuracy:

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlcom{# Leave-one-out cross-validation for Kriging}
\hlstd{cv_krige} \hlkwb{<-} \hlkwd{krige.cv}\hlstd{(U238_ugL} \hlopt{~} \hlnum{1}\hlstd{, contamination_data,} \hlkwc{model} \hlstd{= v_fit)}

\hlcom{# Calculate performance metrics}
\hlstd{rmse} \hlkwb{<-} \hlkwd{sqrt}\hlstd{(}\hlkwd{mean}\hlstd{(cv_krige}\hlopt{$}\hlstd{residual}\hlopt{^}\hlnum{2}\hlstd{))}
\hlstd{mae} \hlkwb{<-} \hlkwd{mean}\hlstd{(}\hlkwd{abs}\hlstd{(cv_krige}\hlopt{$}\hlstd{residual))}
\hlstd{me} \hlkwb{<-} \hlkwd{mean}\hlstd{(cv_krige}\hlopt{$}\hlstd{residual)}

\hlkwd{cat}\hlstd{(}\hlstr{"Cross-Validation Results (Kriging):\textbackslash{}n"}\hlstd{)}
\end{alltt}
\begin{verbatim}
## Cross-Validation Results (Kriging):
\end{verbatim}
\begin{alltt}
\hlkwd{cat}\hlstd{(}\hlkwd{sprintf}\hlstd{(}\hlstr{"  RMSE (Root Mean Square Error): %.2f µg/L\textbackslash{}n"}\hlstd{, rmse))}
\end{alltt}
\begin{verbatim}
##   RMSE (Root Mean Square Error): 5.35 µg/L
\end{verbatim}
\begin{alltt}
\hlkwd{cat}\hlstd{(}\hlkwd{sprintf}\hlstd{(}\hlstr{"  MAE (Mean Absolute Error):      %.2f µg/L\textbackslash{}n"}\hlstd{, mae))}
\end{alltt}
\begin{verbatim}
##   MAE (Mean Absolute Error):      3.41 µg/L
\end{verbatim}
\begin{alltt}
\hlkwd{cat}\hlstd{(}\hlkwd{sprintf}\hlstd{(}\hlstr{"  ME (Mean Error):                %.2f µg/L\textbackslash{}n"}\hlstd{, me))}
\end{alltt}
\begin{verbatim}
##   ME (Mean Error):                0.08 µg/L
\end{verbatim}
\end{kframe}
\end{knitrout}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{figure}[H]

{\centering \includegraphics[width=0.8\textwidth]{figure/cv_plot-1} 

}

\caption[Cross-Validation]{Cross-Validation: Predicted vs Observed}\label{fig:cv_plot}
\end{figure}

\end{knitrout}

The cross-validation results indicate good prediction accuracy, with RMSE of approximately 5.35 $\mu$g/L. Points close to the 1:1 line indicate accurate predictions.

\subsection{Assumptions and Limitations}

This analysis is subject to the following assumptions and limitations:

\textbf{Assumptions:}
\begin{itemize*}
    \item Spatial stationarity: Mean and variance are constant across study area
    \item Isotropy: Spatial correlation is the same in all directions
    \item Water table aquifer is laterally continuous
    \item No significant temporal changes during sampling period
\end{itemize*}

\textbf{Limitations:}
\begin{itemize*}
    \item Limited sample size (n=30) may not fully capture spatial variability
    \item Extrapolation beyond data points is uncertain
    \item Vertical concentration gradients not considered (2D analysis only)
    \item Preferential flow paths not explicitly modeled
    \item Seasonal variations not accounted for
\end{itemize*}

\section{Appendix E: Regulatory Framework}

\subsection{U.S. Federal Standards}

\begin{itemize*}
    \item \textbf{Safe Drinking Water Act (SDWA)}: MCL = 30 $\mu$g/L for combined uranium (U-234 + U-235 + U-238)
    \item \textbf{CERCLA/Superfund}: Site-specific risk-based cleanup levels
    \item \textbf{RCRA}: Groundwater protection standards for hazardous waste facilities
\end{itemize*}

\subsection{Health Effects}

Chronic exposure to uranium in drinking water can cause:
\begin{itemize*}
    \item Kidney toxicity (primary concern at environmental concentrations)
    \item Increased cancer risk (radiological effects)
    \item Bone effects (uranium accumulation in skeletal tissue)
\end{itemize*}

The MCL of 30 $\mu$g/L is based on kidney toxicity rather than radiological risk, as chemical toxicity is the limiting factor at environmental exposure levels.

\section{Appendix F: Glossary}

\begin{description}
    \item[Anisotropy] Directional dependence of spatial correlation
    \item[Kriging] Geostatistical interpolation method providing best linear unbiased prediction
    \item[MCL] Maximum Contaminant Level - enforceable drinking water standard
    \item[Nugget Effect] Discontinuity at the origin of the variogram, representing measurement error and/or micro-scale variation
    \item[Partial Sill] The difference between the sill and nugget in a variogram model
    \item[Range] The distance at which spatial correlation becomes negligible
    \item[Semivariogram] Function describing spatial variance as a function of separation distance
    \item[Sill] The asymptotic value of the variogram at large distances
    \item[Spatial Autocorrelation] The tendency for nearby locations to have similar values
    \item[Stationarity] Statistical properties (mean, variance) constant across space
    \item[TPS] Thin Plate Spline - smoothing interpolation method
    \item[Variogram] Plot of semivariance versus separation distance
\end{description}

\newpage

\section{Document Information}

\subsection{Software Versions}

This analysis was performed using:
\begin{itemize*}
    \item R version: R version 4.2.2 (2022-10-31)
    \item gstat package: 2.1.4
    \item sp package: 2.1.3
    \item ggplot2 package: 3.4.4
    \item fields package: 15.2
\end{itemize*}

\subsection{Compilation Instructions}

To compile this document:
\begin{verbatim}
# In R or RStudio
library(knitr)
knit("u238_analysis.Rnw")

# Then in terminal or command prompt
pdflatex u238_analysis.tex
pdflatex u238_analysis.tex  # Run twice for proper references
\end{verbatim}

Or in RStudio, simply click the "Compile PDF" button.

\subsection{Contact Information}

For questions regarding this analysis or data requests, please contact:
\begin{itemize*}
    \item Environmental Monitoring Division
    \item Email: monitoring@example.org
    \item Phone: (555) 123-4567
\end{itemize*}

\vfill

\noindent\rule{\textwidth}{0.4pt}

\begin{center}
\textit{This report was automatically generated using R and \LaTeX}\\
\textit{Document compiled: \today}
\end{center}

\end{document}
