---
title: "Climate Change Project"
author: "Marc Los Huertos"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Guide 1

## Chunk 1

```{r, chunk1_1}
source("/home/mwl04747/RTricks/04_Regional_Climate_Trends/Guides/Guide1functions.R")
```

## Chunk 2
```{r, chunk1_2}
my.state = "CA"
filename.csv <- "/home/mwl04747/RTricks/04_Regional_Climate_Trends/stations.active.oldest.csv"
my.inventory <- readInventory.fun(filename.csv, my.state)
```

## Chunk 3
```{r, chunk1_3, results='hide'}
datapath = "/home/mwl04747/RTricks/04_Regional_Climate_Trends/Data/SP24/"
downloadStations.fun(datapath, my.inventory)
```

# Guide 2

## Chunk 1

```{r chunk2_1}
source("/home/mwl04747/RTricks/04_Regional_Climate_Trends/Guides/Guide2functions.R")
```

## Chunk 2
```{r, chunk2_2}
datafolder = "/home/mwl04747/RTricks/04_Regional_Climate_Trends/Data/SP24/"
ReadStations2.fun(datafolder)
```

## Chunk 3
```{r}
# sortstations.fun() Nor working yet. 
```

## Chunk 4
```{r, chunk2_4}
USC00042294a <- fixDates.fun(USC00042294)

```

## Chunk 5
```{r, chunk2_5}
coverage.fun(USC00042294a)
```

## Chunk 6
```{r, chunk2_6}
USC00042294b <- fixValues.fun(USC00042294a)
```

## Chunk 7
```{r, chunk2_7}
QAQC.fun(USC00042294b)
```

## Chunk 8
```{r, chunk2_8}
USC00042294.monthly <- MonthlyValues.fun(USC00042294b)
USC00042294.normals <- MonthlyNormals.fun(USC00042294b)
```


## Chunk 9
```{r, chunk2_9}
USC00042294.anomalies <- MonthlyAnomalies.fun(USC00042294.monthly, USC00042294.normals)
```


# Guide 3

## Chunk 1
```{r, chunk3_1}
source("/home/mwl04747/RTricks/04_Regional_Climate_Trends/Guides/Guide3functions.R")
```

## Chunk 2
```{r}
USC00042294.trends <- monthlyTrend.fun(USC00042294.anamolies)
```

## Chunk 3
```{r}

```

# Guide 4

## Chunk 1
```{r, chunk4_1}
source("/home/mwl04747/RTricks/04_Regional_Climate_Trends/Guides/Guide4functions.R")
```

## Chunk 2
```{r}
plotTrend.fun(USC00042294.anomalies, "TMIN", 7)
```

almost done!


















