\documentclass{article}

\usepackage{tikz}% needed <<<<  
\usepackage{nicematrix}% needed <<<<

\usepackage{amssymb} % checkmark    

% From https://tex.stackexchange.com/a/62178/161015
\newcommand{\replicate}[2]{%
\def\temp{}%
\foreach \i in {1,...,#1}{\expandafter\gdef\expandafter\temp\expandafter{\temp #2}}%
\temp}

%\usepackage{showframe} % to show margins

\newcolumntype{P}[1]{>{\sffamily\centering\arraybackslash}p{#1\textwidth-\arrayrulewidth}}
\setlength{\tabcolsep}{0pt}
\renewcommand{\arraystretch}{1.8}

\begin{document}
        
\noindent
\begin{NiceTabular}{|P{0.2}|P{0.3}|P{0.2}|P{0.2}|P{0.1}|}
    \hline
    Datum & \Block{}{Lernbereich \\ \scriptsize (Sprechen, Grammatik, \\ \scriptsize Lesen, \dots{})} & Thema & Material & \LARGE\color{green}\checkmark  \\
    \hline
    \replicate{21}{ & &  & &\\ \hline}  % add lines
    \hline
\end{NiceTabular}