---
title: "Data Visualization with ggplot2"
output:
  html_document:
    toc: true
    toc_depth: 2
    theme: readable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE
)
```

## Overview

This tutorial introduces the core grammar of graphics used by **ggplot2**.

## Load required packages

```{r}
library(tidyverse)
```

## Load example data

```{r}
activity <- read_csv("/home/mwl04747/RTricks/15_Camera_Traps/visualization_test_camera_activity.csv")

glimpse(activity)
```

## First plot

```{r}
ggplot(activity, aes(x = hour, y = n_events)) +
  geom_col()
```

## Aesthetics

```{r}
ggplot(activity, aes(hour, n_events, fill = behavior)) +
  geom_col()
```

## Facets

```{r}
ggplot(activity, aes(hour, n_events)) +
  geom_col() +
  facet_wrap(~ camera_id)
```

## Themes

```{r}
ggplot(activity, aes(hour, n_events)) +
  geom_col() +
  theme_bw()
```

## Export-ready figure

```{r}
p <- ggplot(activity, aes(hour, n_events, fill = behavior)) +
  geom_col() +
  facet_wrap(~ camera_id) +
  theme_bw()

ggsave("camera_activity_plot.png", p, width = 7, height = 4, dpi = 300)
```
